# Generated by Django 3.0.8 on 2020-07-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Your_model',
        ),
    ]
